name: "Terraform Plan with Cloudability"

on:
  pull_request:
    branches:
      - main # Change this to your main branch name

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC
      contents: read
      pull-requests: write # Required to comment on PRs
    steps:
      # Step 1: Checkout the repository
      - name: "Checkout"
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v2
        with:
          # This is important to ensure a clean JSON output
          terraform_wrapper: false

      # Step 3: Configure AWS Credentials with OIDC
      # This is the recommended secure way to handle credentials
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }} # Replace with your IAM Role ARN
          aws-region: us-east-1 # Or your desired region

      # Step 4: Initialize Terraform
      - name: "Terraform Init"
        run: terraform init

      # Step 5: Run a Terraform Plan and save it to a file
      - name: "Terraform Plan"
        id: plan
        run: terraform plan -no-color -out=tfplan.out

      # Step 6: Convert the binary plan to JSON
      - name: "Create JSON plan file"
        run: terraform show -json tfplan.out > tfplan.json

      # Step 7: Upload the JSON plan as an artifact for later steps
      - name: "Upload plan artifact"
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-json
          path: tfplan.json

      # Step 8: Call the Cloudability Governance Action
      # We'll add this step once the above steps are working and tested
